In [1]:
import torch
from torch import nn
import tensorwatch as tw
from config import Config
from data.load import TableDataLoader
from load import load
from model.cmha import CompressedMultiHeadAttention
args = Config('./configs/ncgm.yaml')

In [2]:
# tr_dl = TableDataLoader(args, "train")
# table_train_dl = tr_dl.get_dataloader()

2023-04-10 11:39:10.869 | DEBUG    | data.scitsr:__init__:28 - Word2vec loaded from /Volumes/Disk/Dataset/word2vec/GoogleNews-vectors-negative300.bin
2023-04-10 11:39:11.034 | INFO     | data.load:get_dataloader:27 - Dataset SciTSR loaded


In [3]:
model, criterion, optimizer = load(args)

In [4]:
# for batch in table_train_dl:
#     geometry, appearance, content, bounding_box, structure = batch
#     # save batch pkl
#     torch.save(batch, 'batch.pkl')
#     # model(geometry, appearance, content, bounding_box)
#     break

In [4]:
batch = torch.load('batch.pkl')
geometry, appearance, content, bounding_box, structure = batch
cell_output, row_output, col_output, emb_pairs = model(geometry, appearance, content, bounding_box)
criterion(cell_output, row_output, col_output, emb_pairs, structure)


(tensor([[[ -6.8748,   0.1133],
          [ -6.4302,   1.0301],
          [-12.8182,   3.1024],
          ...,
          [ -0.0384,  -0.0364],
          [ -0.0384,  -0.0364],
          [ -0.0384,  -0.0364]]], grad_fn=<ViewBackward0>),
 tensor([[[ 0.3346,  1.4468],
          [ 2.7464,  2.7369],
          [ 5.8497,  5.1816],
          ...,
          [-0.0601,  0.0170],
          [-0.0601,  0.0170],
          [-0.0601,  0.0170]]], grad_fn=<ViewBackward0>),
 tensor([[[ 1.7965,  1.8060],
          [ 2.6297,  3.6724],
          [ 4.1441, 10.4329],
          ...,
          [ 0.0125,  0.0795],
          [ 0.0125,  0.0795],
          [ 0.0125,  0.0795]]], grad_fn=<ViewBackward0>),
 tensor([[[ 0.0000e+00,  0.0000e+00,  6.5944e+00,  ..., -1.7188e-01,
            2.5474e-02, -3.2076e-02],
          [ 0.0000e+00,  0.0000e+00,  4.9054e+01,  ..., -1.7188e-01,
            2.5474e-02, -3.2076e-02],
          [ 0.0000e+00,  0.0000e+00,  1.3245e+02,  ..., -1.7188e-01,
            2.5474e-02, -3.2076e-02]

In [ ]:
cmha = CompressedMultiHeadAttention(args=args)
g = torch.randn(1, 500, 64)
a = torch.randn(1, 500 ** 2, 64)
c = torch.randn(1, 500 ** 2, 64)
o = cmha(g, a, c)

In [5]:
fc = nn.Sequential(
            nn.Linear(64*3*2, 256),
            nn.ReLU(),
            nn.Linear(256, 2),
        )

In [6]:
a = torch.randn(1, 500 ** 2, 64*3*2)
fc(a).shape

torch.Size([1, 250000, 2])