In [1]:
import torch
from torch import nn
from config import Config
from data.load import TableDataLoader
from load import load
from model.cmha import CompressedMultiHeadAttention
args = Config('./configs/ncgm.yaml')

ModuleNotFoundError: No module named 'config'

In [2]:
tr_dl = TableDataLoader(args, "train")
table_train_dl = tr_dl.get_dataloader()

2023-04-15 17:18:21.368 | DEBUG    | data.scitsr:__init__:28 - Word2vec loaded from /Volumes/Disk/Dataset/word2vec/GoogleNews-vectors-negative300.bin
2023-04-15 17:18:21.697 | INFO     | data.load:get_dataloader:27 - Dataset SciTSR loaded


In [3]:
model, criterion, optimizer = load(args)

In [4]:
for batch in table_train_dl:
    # geometry, appearance, content, bounding_box, structure = batch
    # save batch pkl
    torch.save(batch, 'batch.pkl')
    # model(geometry, appearance, content, bounding_box)
    break

In [5]:
batch = torch.load('batch.pkl')
geometry, appearance, content, bounding_box, row_adj_matrix, col_adj_matrix, cell_adj_matrix, structure = batch


In [ ]:
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")

In [9]:
# bounding_box = list(bounding_box)
bounding_box = bounding_box.squeeze(0)
cell_output, row_output, col_output, emb_pairs = model(geometry, appearance, content, bounding_box)

: 

: 

In [ ]:
criterion(cell_output, row_output, col_output, emb_pairs, structure)

In [ ]:
cmha = CompressedMultiHeadAttention(args=args)
g = torch.randn(1, 500, 64)
a = torch.randn(1, 500 ** 2, 64)
c = torch.randn(1, 500 ** 2, 64)
o = cmha(g, a, c)

In [5]:
import torch

In [6]:
X_split = torch.randn((2,500*500,2,192))

In [7]:
X_split = X_split.view(-1, 2, X_split.shape[-1])

In [15]:
X_split

tensor([[[ 0.2274, -0.5370,  1.8045,  ..., -0.7050,  0.2152,  0.8532],
         [-0.6965, -0.2617,  2.2837,  ..., -0.9323,  0.1051,  0.8985]],

        [[ 0.2821, -1.0761,  0.7567,  ..., -0.0681,  1.2673, -0.7953],
         [ 0.9313,  0.7097,  0.7224,  ..., -0.8480, -0.8905,  1.3118]],

        [[ 1.4729,  0.6691, -0.8735,  ..., -0.9526, -0.4732,  0.4654],
         [ 0.7255,  0.8529, -1.7535,  ...,  0.4913,  0.6657, -0.3153]],

        ...,

        [[-0.6038, -0.6898, -0.8469,  ..., -0.0729, -0.7892, -1.0958],
         [ 1.1079,  1.4767,  1.0536,  ..., -1.1476, -0.9632, -2.1035]],

        [[ 0.1572,  0.3295, -0.6979,  ..., -1.1455,  1.7771,  1.8045],
         [-1.4827, -0.2279,  0.7061,  ...,  1.1584, -1.1652,  0.2748]],

        [[-2.6475,  0.6065,  0.8294,  ...,  0.6110, -1.4431,  0.4180],
         [ 1.2187, -0.0216,  0.3486,  ..., -0.2644,  0.6000, -0.1866]]])

In [14]:
(X_split[:, 1, :] - X_split[:, 0, :]).shape

torch.Size([500000, 192])

In [45]:
input = torch.randn((2, 2, 4), requires_grad=True)
target = torch.randint(2, (2,4), dtype=torch.int64)

In [46]:
input, target

(tensor([[[ 1.1733,  0.1229, -0.2633, -1.5430],
          [ 0.8043, -0.9127,  0.3433,  0.9226]],
 
         [[ 1.2811, -0.0656,  3.0065, -1.4107],
          [ 0.4100, -1.5531, -0.5981,  0.7235]]], requires_grad=True),
 tensor([[1, 0, 1, 0],
         [1, 1, 0, 1]]))

In [51]:
input = torch.tensor([[[1,0,1,0],[0,1,0,1]], [[1,1,0,1],[0,0,1,0]]], dtype=torch.float)

In [52]:
torch.nn.functional.cross_entropy(input, target)

tensor(1.3133)